export const AUTH_ISVENDOR = 'AUTH_ISVENDOR';
export const AUTH_STOREUSER = 'AUTH_STOREUSER';
export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const AUTH_SIGNUPSUCCESS = 'AUTH_SIGNUPSUCCESS';
export const AUTH_SIGNUPFAIL = 'AUTH_SIGNUPFAIL'
export const SET_AUTH_REDIRECT_PATH='SET_AUTH_REDIRECT_PATH';

export const FETCH_TESTS='FETCH_TESTS';
export const ADD_TESTS='ADD_TESTS';
